#!/bin/bash
# setup_cron.sh - Set up cron job for dev-autopilot
#
# Usage:
#   bash setup_cron.sh /path/to/project [interval_minutes]
#
# Examples:
#   bash setup_cron.sh /Users/rick/my-project 30
#   bash setup_cron.sh /Users/rick/my-project      # default: 30 min

set -euo pipefail

PROJECT_DIR="${1:-$(pwd)}"
INTERVAL="${2:-30}"
SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LOG_FILE="$PROJECT_DIR/DevPlan/autopilot.log"
RUNNER_SCRIPT="$PROJECT_DIR/.autopilot_run.sh"

# Validate project dir
if [ ! -d "$PROJECT_DIR" ]; then
    echo "❌ Error: Project directory not found: $PROJECT_DIR"
    exit 1
fi

if [ ! -d "$PROJECT_DIR/DevPlan" ]; then
    echo "❌ Error: DevPlan/ directory not found in $PROJECT_DIR"
    echo "   Run dev-planner first to generate the development plan."
    exit 1
fi

echo "🚀 Setting up dev-autopilot cron job..."
echo "   Project: $PROJECT_DIR"
echo "   Interval: every $INTERVAL minutes"
echo "   Log: $LOG_FILE"

# Create log directory
mkdir -p "$(dirname "$LOG_FILE")"

# Create the runner script that cron will call
cat > "$RUNNER_SCRIPT" << RUNNER
#!/bin/bash
# Auto-generated by dev-autopilot setup_cron.sh
# Runs Claude Code to continue development of uncompleted modules

PROJECT_DIR="$PROJECT_DIR"
LOG_FILE="$LOG_FILE"
TIMESTAMP=\$(date '+%Y-%m-%d %H:%M:%S')

echo "[\$TIMESTAMP] dev-autopilot cron triggered" >> "\$LOG_FILE"

# Check if there are any pending modules
PENDING_COUNT=\$(python3 "$SKILL_DIR/scripts/parse_checklist.py" "\$PROJECT_DIR/DevPlan/" --json 2>/dev/null | python3 -c "
import sys, json
data = json.load(sys.stdin)
total = sum(a.get('summary', {}).get('pending', 0) for a in data.get('apps', []))
print(total)
" 2>/dev/null || echo "0")

if [ "\$PENDING_COUNT" -eq "0" ]; then
    echo "[\$TIMESTAMP] ✅ All modules complete. Nothing to do." >> "\$LOG_FILE"
    exit 0
fi

echo "[\$TIMESTAMP] Found \$PENDING_COUNT pending module(s). Starting development..." >> "\$LOG_FILE"

# Check if claude CLI is available
if ! command -v claude &> /dev/null; then
    echo "[\$TIMESTAMP] ❌ Error: 'claude' CLI not found. Please install Claude Code." >> "\$LOG_FILE"
    exit 1
fi

# Run Claude Code in non-interactive mode to continue development
cd "\$PROJECT_DIR" && claude --dangerously-skip-permissions -p "
You are running dev-autopilot.

1. Read DevPlan/ and find the next uncompleted module in checklist.md
2. Follow dev-executor TDD workflow strictly:
   - Implement code
   - Write unit tests (coverage > 80%)
   - Run tests, fix until all pass
   - Update checklist.md
   - Git commit
3. If you need credentials (API keys, passwords, DB URLs), write them to DevPlan/BLOCKED.md and skip that module
4. Process as many modules as possible in this session
5. Append a summary to DevPlan/autopilot.log when done

Continue from where you left off. Do not ask for confirmation.
" >> "\$LOG_FILE" 2>&1

echo "[\$TIMESTAMP] Session complete." >> "\$LOG_FILE"
RUNNER

chmod +x "$RUNNER_SCRIPT"
echo "✅ Created runner script: $RUNNER_SCRIPT"

# Build cron expression: every N minutes
CRON_EXPR="*/$INTERVAL * * * *"

# Check if cron entry already exists
CRON_MARKER="dev-autopilot:$PROJECT_DIR"
EXISTING=$(crontab -l 2>/dev/null | grep -F "$CRON_MARKER" || true)

if [ -n "$EXISTING" ]; then
    echo "⚠️  Cron job already exists for this project. Removing old entry..."
    crontab -l 2>/dev/null | grep -v "$CRON_MARKER" | crontab -
fi

# Add new cron entry
(crontab -l 2>/dev/null; echo "$CRON_EXPR bash \"$RUNNER_SCRIPT\" # $CRON_MARKER") | crontab -

echo ""
echo "✅ Cron job installed successfully!"
echo ""
echo "📋 Cron schedule: $CRON_EXPR (every $INTERVAL minutes)"
echo "📄 Runner script: $RUNNER_SCRIPT"
echo "📝 Log file:      $LOG_FILE"
echo ""
echo "Useful commands:"
echo "  View current crontab:  crontab -l"
echo "  Remove cron job:       crontab -l | grep -v '$CRON_MARKER' | crontab -"
echo "  Watch live log:        tail -f '$LOG_FILE'"
echo "  Run manually now:      bash '$RUNNER_SCRIPT'"
echo ""
echo "⚠️  Note: Requires Claude Code CLI ('claude') to be installed and authenticated."
echo "   Install: https://claude.ai/code"
