---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared

---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-token
  namespace: cloudflared
type: Opaque
stringData:
  token: "eyJhIjoiMjc3YWE4NzlmZGNkNzhjNDU0NTUyZGM0NzRmMTkxZmYiLCJ0IjoiZWIwMzdlMjQtYzI2YS00MjQxLWIyN2ItODJmYmU5OGQxNDc2IiwicyI6Ik5YV0dLUWZDMnd5VjhFWENhMWlyczNYNCs0VHVkdDI5OFZ5RzFKS2doTit2aEVodDNoTW51ZHVLbnorRXlkWG1PbUhxVXljWFJCSUlBdFRTWEZEWm9RPT0ifQ=="

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:latest
          args:
            - tunnel
            - --no-autoupdate
            - run
            - --token
            - $(TUNNEL_TOKEN)
          env:
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-token
                  key: token
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
